#!/bin/sh

#
# create symbolic link to dot file.
#

create_link() {
    dot_dir="$1"

    cd $dot_dir
    for dotfile in `ls ${dot_dir} | grep ^dot\..*`; do
        ln -sfvT $dot_dir/$dotfile $HOME/`echo $dotfile | sed 's/^dot//g'`
    done
}

create_link "$HOME/Dropbox/dot/public"
create_link "$HOME/Dropbox/dot/local"
create_link "$HOME/Dropbox/dot/untracked"
