#!/bin/sh

#
# create symbolic link to dot file.
#

readonly DOT_DIR="$HOME/Dropbox/dot"

cd $DOT_DIR
for dotfile in `ls ${DOT_DIR} | grep ^dot\..*`; do
    ln -sfvT $DOT_DIR/$dotfile $HOME/`echo $dotfile | sed 's/^dot//g'`
done
