#!/bin/bash

#project="project"
root=.

#mkdir -p $root/$project || exit 1;

#cd $root/$project

# shebang が bash でないとブレース展開できないので注意
mkdir -p src/{main,test}/{scala,java,resources}
touch src/{main,test}/{scala,java,resources}/.gitkeep

mkdir -p project
touch project/Build.scala

cat <<'EOF' > build.sbt
name := "project name"

version := "1.0"

scalaVersion := "2.9.2"

libraryDependencies ++= Seq(
  "org.specs2" %% "specs2" % "1.12.3" % "test",
  "com.github.scala-incubator.io" % "scala-io-core_2.9.1" % "0.4.1-seq",
  "com.github.scala-incubator.io" % "scala-io-file_2.9.1" % "0.4.1-seq"
)

scalacOptions += "-deprecation"

compile <<= (compile in Compile) map {
  result => {
    Process("ctags-exuberant -Re").run
    result
  }
}
EOF

cat <<'EOF' > .gitignore
*.class
*.log

# ctags specific
TAGS

# sbt specific
dist/*
target/
lib_managed/
src_managed/
project/boot/
project/plugins/project/

# Scala-IDE specific
.scala_dependencies
EOF

# end of file
