#!/bin/bash -u

readonly TARGET_PROC=$(ps aux | peco)
readonly TARGET_PID=$(echo "$TARGET_PROC" | awk '{print $2}')

echo "> ${TARGET_PROC}"
read -p "Kill? (Y/n): " yn
case "$yn" in
    Y) kill -s SIGKILL $TARGET_PID ;;
    *) echo "Abort." ;;
esac
